---
- name: copy_config
  copy:
    src: "{{ item }}"
    dest: /etc/apache2/conf-available/
  with_fileglob: "files/conf-available/*"
  when: item is not search("README")
- name: enable_config
  shell: "a2enconf {{ item }}"
  with_items: "{{ conf_enabled }}"
  when: conf_enabled is defined
