---
# activate on demand
#- include_tasks:
#    file: test.yaml
- include_tasks:
    file: install.yaml
    apply:
      tags:
        - install
- name: task_modules
  include_tasks:
    file: modules.yaml
- name: task_config
  include_tasks:
    file: config.yaml
- name: task_vhost
  include_tasks:
    file: vhost.yaml
# if module enabling has not been done yet due to (temporary) config errors
# give it a second try here
- name: task_modules2
  include_tasks:
    file: modules.yaml
  when: config_correct.rc == 1
- name: task_individual
  include_tasks:
    file: additional.yaml
- name: task_restart
  include_tasks:
    file: restart.yaml
