- name: syntax_check
  shell: apachectl -t
  register: syntaxcheck

- name: restart
  notify: Restart apache
  when: syntaxcheck.rc == 0

- debug:
    msg: "Apache config has errors - stopping here."
  when: syntaxcheck.rc != 0

- meta: end_play
  when: syntaxcheck.rc != 0
