---
# copy templates
- name: copy_templates
  include_tasks: copy_templates.yaml
  with_dict: "{{ virtual_host }}"

# copy vhosts templates to sites-available
- name: copy_vhosts
  copy:
    src: "{{ item }}"
    dest: "/etc/{{ service }}/sites-available"
  when: item is not search("template.conf") and item is not search("template-ssl.conf")
  with_fileglob: "templates/*"

- name: disable_default
  shell: a2dissite 000-default.conf

- include_tasks:
    file: letsencrypt.yaml
  when: letsencrypt == true

- name: enable
  shell: a2ensite "{{ item | basename }}"
  when: item is not search("template.conf") and item is not search("template-ssl.conf")
  with_fileglob: "templates/*"
