##### Ansible managed. DON'T edit manually! #####

<VirtualHost *:443>
	ServerName mail.nomorebluescreen.de
	ServerAdmin hostmaster@nomorebluescreen.de
	SSLEngine on
	SSLCertificateFile /var/lib/dehydrated/certs/mail.nomorebluescreen.de/fullchain.pem
	SSLCertificateKeyFile /var/lib/dehydrated/certs/mail.nomorebluescreen.de/privkey.pem
	#SSLCertificateCAFile /etc/ssl/certs/ISRG_Root_X1.pem

	Include /etc/apache2/conf-available/ssl-encryption.conf
	
	DocumentRoot /usr/share/roundcube

	CustomLog ${APACHE_LOG_DIR}/mail.nomorebluescreen.de-ssl-access.log combined
	ErrorLog ${APACHE_LOG_DIR}/mail.nomorebluescreen.de-ssl-error.log

</VirtualHost>
