##### Ansible managed. DON'T edit manually! #####

<VirtualHost *:80>
	ServerName www.nomorebluescreen.de
	ServerAdmin hostmaster@nomorebluescreen.de

	Include /etc/apache2/conf-available/rewrite-http-to-https.conf

	CustomLog ${APACHE_LOG_DIR}/www.nomorebluescreen.de-access.log combined
	ErrorLog ${APACHE_LOG_DIR}/www.nomorebluescreen.de-error.log

	LogLevel warn

</VirtualHost>
