##### Ansible managed. DON'T edit manually! #####

<VirtualHost *:443>
	ServerName www.nomorebluescreen.de
	ServerAdmin hostmaster@nomorebluescreen.de
	SSLEngine on
	SSLCertificateFile /var/lib/dehydrated/certs/www.nomorebluescreen.de/fullchain.pem
	SSLCertificateKeyFile /var/lib/dehydrated/certs/www.nomorebluescreen.de/privkey.pem
	#SSLCertificateCAFile /etc/ssl/certs/ISRG_Root_X1.pem

	Include /etc/apache2/conf-available/ssl-encryption.conf
	
	DocumentRoot /var/www

	CustomLog ${APACHE_LOG_DIR}/www.nomorebluescreen.de-ssl-access.log combined
	ErrorLog ${APACHE_LOG_DIR}/www.nomorebluescreen.de-ssl-error.log

</VirtualHost>
